### PR TITLE
Use go module versioning

### PR DESCRIPTION
**Pull request by cainelli**
Fixes https://github.com/Skyscanner/kms-issuer/issues/224. It felt a big change to introduce it in the v3 release. Let me know your thoughts.

### CODE REVIEW

**Comment by Smirl** [comment]
I've just rebased this branch from master.

**Comment by cainelli** [comment]
Thank you, @Smirl 👍

**Review by Smirl — APPROVED** [review]

**Comment by Smirl** [comment]
Thanks for your contribution. I might merge in some of the other dependabot PRs, give it a test, then cut a release soon.

**Comment by cainelli** [comment]
Awesome! thanks :)

**Pull request merged**
